version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
        environment:
          IMAGE_URI: ministryofjustice/prometheus-ecr-exporter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t "${IMAGE_URI}:${CIRCLE_SHA1}" .
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
            if [ ! -z "${CIRCLE_TAG}" ]; then
              if [ "${CIRCLE_BRANCH}" != "master" ]; then
                  echo "Will not push images from non-master branches"
                  exit 0
              fi
              docker tag "${IMAGE_URI}:${CIRCLE_SHA1}" "${IMAGE_URI}:${CIRCLE_TAG}"
              docker push "${IMAGE_URI}:${CIRCLE_TAG}"
              docker tag "${IMAGE_URI}:${CIRCLE_SHA1}" "${IMAGE_URI}:latest"
              docker push "${IMAGE_URI}:latest"
            else
              docker push "${IMAGE_URI}:${CIRCLE_SHA1}"
              docker tag "${IMAGE_URI}:${CIRCLE_SHA1}" "${IMAGE_URI}:master"
              docker push "${IMAGE_URI}:master"
            fi
workflows:
  build_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
