version: 2
jobs:
  build:
    branches:
      only:
       master
    docker:
      - image: circleci/buildpack-deps:stretch
        environment:
          IMAGE_URI: ministryofjustice/prometheus-ecr-exporter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t "${IMAGE_URI}:${CIRCLE_SHA1}" .
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
            docker push "${IMAGE_URI}:${CIRCLE_SHA1}"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag "${IMAGE_URI}:${CIRCLE_SHA1}" "${IMAGE_URI}:latest"
              docker push "${IMAGE_URI}:latest"
            fi